var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                               o             o                                  ",
   "                              xxxx         xxxx                                 ",
   "                      o            x!!!!x             o                      x  ",
   "  xx                xxxx           x!!!!x           xxxx                     x  ",
   "  x          o                     x!!!!x                       o            x  ",
   "  x  @     xxxx                    x!!!!x                     xxxx           x  ",
   "  x                                x!!!!x                                   x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                          xxxxxxxxxxxxxxxxxxxx                                                                    ",
   "                  xxxxx   x                  x                                                                    ",
   "                  x!!!x   x                  x                                                                    ",
   "                  xvxxx   x         o        x                                                                    ",
   "                          x    xxxxxxxxxx    x                                                                    ",
   "                          x    x        x    x                                                                    ",
   "   x                      x   xx        x                        o                                                ",
   "   x                      x    x      x    =    x               xxx    x      x                                   ",
   "   x                      xx   x                          o            x      x                                   ",
   "   x                xxxxxxx    x                     o   xxx          x        x                                  ",
   "   x                          xx                   xxx               x          x                                 ",
   "   x      @               o    x           o                         x  o  o  o x                                 ",
   "   x    xxxxx    xxxxxxxxxxxxxxx        xxxxxxxx                      xxxxxxxxxx                                  ",
   "   x!!!!x x x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!       ",
   "   x!!!!x x x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!       ",
   "   x!!!!x x x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!       ",
   "   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      ",
   "    x                                    =  |                =             |                           x      ",
   "    x        |                                   o     |                    o       =                  x      ",
   "    x                  o    =                           o                                              x      ",
   "    x                                  o                               o               o              ox      ",
   "    xo        =  o          |   o                               o           =                  o      xx      ",
   "    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         x      ",
   "                                                                                            x    x     x      ",
   "                                                                                            x         ox      ",
   "    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         xx      ",
   "    x                                                                                       x    x     x      ",
   "    x                                                                                       xx         x      ",
   "    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          x      ",
   "    x       |          |            |                                                            x    ox      ",
   "    x                                       o                       |    o                            xx      ",
   "    x                         o                       |          o                 |       o           x      ",
   "    x @           o                                     o                           o                  x      ",
   "    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                xxx                           ",
   "                                                                                x x    xxxxxxxx               ",
   "                                                                                xxx    x      x   xxxx        ",
   "           xxxx    xxxxx   xxxxxx  x    x        x                         x           x      x   x  x        ",
   "           x   x  x    x   x    x  x    x         x                       x     xxx    x      x   x  x        ",
   "            x   xx    x    x    x  x    x          x                     x      x x    x      x   x  x        ",
   "             x       x     x    x  x    x           x        xxx        x       x x    x      x   xxxx        ",
   "              x     x      x    x  x    x            x      x   x      x        x x    x      x               ",
   "               x   x       x    x  x    x             x    x     x    x         x x    x      x   xxxx        ",
   "               x   x       x    x  x    x              xxxx       xxxx          x x    x      x   x  x        ",
   "               xxxxx       xxxxxx  xxxxxx                                       xxx               xxxx        ",
   "                                                                                                              ",
   "      @        o                    o                     o                                     o             ",
   "   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx             ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
